services:
  service-1:
    build: ./src/service-1/
    container_name: service-1
    ports:
      - "8199:3000"
    networks:
      - service-network
  service-2:
    build: ./src/service-2/
    container_name: service-2
    networks:
      - service-network
networks:
  service-network:
    name: service-network
