services:
  service-1:
    build: ./src/service-1/
    networks:
      - service-network
    depends_on:
      - service-2
    deploy:
      mode: replicated
      replicas: 3
  service-2:
    build: ./src/service-2/
    container_name: service-2
    networks:
      - service-network
  monitor:
    build: ./src/monitor/
    networks:
      - service-network
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock # necessary to bind host docker socket to controll docker from inside of containers
    depends_on:
      - service-1
  nginx:
    build: ./src/nginx/
    ports:
      - "8081:80"
    networks:
      - service-network
    depends_on:
      - service-1
networks:
  # specifying the network explicitly is not neccessary, default can be used for this purpose
  service-network:
    name: service-network
